### ISSUE TITLE
Add 'Artist Name' alongside panel icon

### ISSUE THREAD

**Issue by vredesbyyrd** [vredesbyyrd/gnome-shell-extensions-mpris-indicator-button#1]
@jasonLG1979 

I would like to add the 'Artist name' alongside the panel icon as the default behavior, and no more. It does not have to be configurable. I have scanned through the code of your mediaplayer-indicator extension that has artist name, song title etc. as an option. Though I presume a simpler approach should be taken here since it would not need to be configurable. When time abides, where would one start at accomplishing this?  

Cheers.

**Comment by JasonLG1979** [comment]
I'm going to do you one better. I'm going to show **you** how to do it. After all if you want this fork kept current you'll need to have at least a passing understanding of Gjs to be able to integrate future changes from upstream. 

Do you have any coding experience?

**Comment by vredesbyyrd** [comment]
well that would be awesome. The extent of coding experience (that description is a stretch in itself) is writing css stylesheets and bash scripts, and hackin at javascript / gjs & python scripts. The latter of which I wouldn't be able to write a lick of to save my life. Put it this way, I dont know any _real_ OOPL, at all. Though I have been wanting to learn at least _some_  Gjs since I always find myself haphazardly trying to bend it to my will. And yes your correct, If I intend to actually maintain this fork I need to step up my understanding, this would give me good reason to start. At the same time I do not want to waste anyone's time, but if your willing to bare with a noob, ill very gladly listen.

**Comment by JasonLG1979** [comment]
I'm a noob myself, don't worry. I had zero experience with js before I started hacking around on GNOME Shell extensions. I still really have zero experience as far as writing "real" js. The Gjs docs suck really, really bad and Gjs has a few quirks. (the need to explicitly destroy GObjects sometimes for example so they don't leak memory) I pretty much taught myself though trial and error and though my understanding of the GObject Python bindings.

**Comment by vredesbyyrd** [comment]
Cool cool. Yeah Im probably like where you started out. In the process of trying to teach myself. Just an enthusiast. I like gnomes extension ecosystem, but I am hopelessly picky and dont want things I use to do anymore than _I need_ them to. So I just wanna be able to write things myself. 

EDIT.... so your direction would be greatly appreciated for sure. And I noticed before that the gjs doc sucks. But I thought it might just be me :)

**Comment by JasonLG1979** [comment]
To start you must understand that St Widgets pretty much suck, but unfortunately that's what GNOME Shell is made out of... To do anything remotely interesting or complicated you have to choke them into submission. The Shell itself does a fare amount of type checking (for lack of a better term). It will in many cases not allow you to put certain widgets inside other widgets for example.

Luckily we won't be doing anything really interesting or complicated.

You'll also need to learn some git.

Assuming you have git installed.

Clone your repo:

```git clone https://github.com/vredesbyyrd/gnome-shell-extensions-mpris-indicator-button.git```

Now cd to the folder:

```cd  gnome-shell-extensions-mpris-indicator-button```

Set my repo as "upstream":

 ```git remote add upstream https://github.com/JasonLG1979/gnome-shell-extensions-mpris-indicator-button.git```

Fetch "upstream":

```git fetch upstream```

Make sure you're on the master branch:

```git checkout master```

Update you're master branch to match upstream:

```git merge upstream/master```

Create a new branch to work on (keep the master branch the same as "upstream" master):

```git checkout -b [name_of_your_new_branch]```

**Comment by JasonLG1979** [comment]
Forks don't automatically update, so from time to time you'll need to run:

```git fetch upstream```

```git checkout master```

```git merge upstream/master```

Again it's a good idea to keep master clean. Unless you plan on totally going your own way you should work off a branch.

**Comment by vredesbyyrd** [comment]
Done. 

All great info and explained plainly. I didnt understand how to fork properly and now I do.

**Comment by JasonLG1979** [comment]
And then as things change in master you can rebase your branch off master. git will tell you if and where there are any conflicts during the rebase and you'll need address them as they come up. But we will get to that as it happens.

**Comment by vredesbyyrd** [comment]
Perfect. Roger that.

**Comment by JasonLG1979** [comment]
Ok, assuming your master update worked you'll need to push your updated master to github.

If you have not already set your username and email. Use the same exact email and username as you use on github.

```git config --global user.email "you@example.com"```

```git config --global user.name "Your Name"```

Again make sure you're on master.

```git checkout master```

Push the updated master.

```git push -f origin master```

**Comment by vredesbyyrd** [comment]
Done. Everything seems to be in working order.

**Comment by JasonLG1979** [comment]
Since this extension has no setting or anything that needs to be compiled I usually just copy and paste the mprisindicatorbutton@JasonLG1979.github.io directly into ~/.local/share/gnome-shell/extensions/ and work from there so I can Alt+F2 and restart the Shell to see if my changes do what I want them to. Once it works the way I want I copy and paste it back to the original folder and make a commit.

To make a commit:

Tell git you changed stuff:

```git add .```

Make the commit (it will use your default command line test editor, nano in Ubuntu):

```git commit```

Give a brief explanation of your commit and save and close the file.

Push your commit to your branch on github:

```git push -f origin [name_of_your_branch]```

**Comment by JasonLG1979** [comment]
At any point you make a mistake or typo in the code or commit message you can amend a commit.

*Make your changes to the code if any.*

Again tell git you changed stuff:

```git add .```

Amend the last commit:

```git commit --amend```

*Make changes to the commit message if any.*

Save and close the file.

Push your amended commit to github:

```git push -f origin [name_of_your_branch]```

**Comment by JasonLG1979** [comment]
I use ```--amend``` A LOT. I make a lot of typos,lol!!!

**Comment by JasonLG1979** [comment]
Now let me mess around with the code a bit and I'll be back in a day or so and walk you through what I've come up with.

**Comment by vredesbyyrd** [comment]
I predict I will also be using amend all the damn time. ha. I pushed my new branch to github. Though obviously no changes yet. 

And sounds great. Thanks a ton man, I really didnt understand the git workflow at all before, and was kinda intimidated by it...as illogical as that is. But just following your directions I can wrap my head around it now. Eazy peazy. And look forward to seeing what you come up with....hopefully I will actually be able to contrib mysefl soon. haha. Well on the road to it... 

PS...your lastest commit woked great. My shell/gtk theme is based of adapta...and before the latest commit margins/padding was all efft up. Looks great now. Cheers.

**Comment by JasonLG1979** [comment]
> PS...your lastest commit woked great. My shell/gtk theme is based of adapta...and before the latest commit margins/padding was all efft up. Looks great now. Cheers.

Yep, one of the things I wanted to do with this extension was to not use any custom style classes. As a result I was using the same style classes as the default MPRIS widget (still am using most of them). I noticed that some themes really did not work very well.

**Comment by JasonLG1979** [comment]
The text color in some themes is still messed up.

**Comment by vredesbyyrd** [comment]
> Yep, one of the things I wanted to do with this extension was to not use any custom style classes. As a result I was using the same style classes as the default MPRIS widget (still am using most of them). I noticed that some themes really did not work very well. 

Yup, Always gotta run into something when you try and keep things simple. Sounds like you came up with a nice & clean solution though.  

[Here](https://imgur.com/a/Yd5883p) is a screen of what it looks like for me. This with the adapta-theme basically. I just made it darker and few minor tweaks. Font colors look on point, and padding is better. If I were to be an annoying critic, I would say maybe there could afford to be a a pixel or 2 more padding between the album cover and Artist/Title. Or even just move the album cover 2px left. Though some of the widgets with these kinda themes are overly compact in the first place so yeah....How you have it now I would say is completely acceptable, IMO. And I dont even know if that could be changed on an individual level via js. Maybe its down to the theming side.  

Before I start rambling more, cheers.  

EDIT. Okay yeah the padding must be down to the theme. When I switched to the default shell theme, I see you just have everything centered. And with adapta, it just moves all elements closer to each other so padding seems less. Still looks good imo

**Comment by JasonLG1979** [comment]
> Okay yeah the padding must be down to the theme. When I switched to the default shell theme, I see you just have everything centered. And with adapta, it just moves all elements closer to each other so padding seems less. Still looks good imo

That's pretty much all Shell themes are, a bunch of style classes. That was the thought as far as not using custom style classes. So that it *should* look native no matter the theme. But not all themes are created equal.

**Comment by vredesbyyrd** [comment]
Budgie is now my daily driver so closing as no longer relevant.  Thank you for all the very helpful info on getting started with the git workflow!
